#ifndef ASRC_FULL_IIR_PRECHECK_COEFFS_H
#define ASRC_FULL_IIR_PRECHECK_COEFFS_H

/*
 * GENERATED by tools/asrc/gen_full_iir_precheck_coeffs.py -- do not hand-edit.
 *
 * Phase-4 full-IIR candidate, measurement-only:
 *
 *   elliptic order 12, 6 SOS, fp = 15 kHz,
 *   rp = 0.25 dB, rs = 120 dB, at 48 kHz input.
 *
 * Topology it belongs to: 48 kHz -> this IIR -> unchanged generic ASRC at
 * step about 1.5 -> 32 kHz.  Host qualification (Phase 4): worst full-chain
 * alias -119.751 dBc over 0-15 kHz, wanted at 15 kHz +0.000031 dB.
 *
 * SECTION ORDER IS MANDATORY.  Rows are low-Q-first (pole radii
 * 0.527679 < 0.696560 < 0.833704 < 0.913377 < 0.958690 < 0.987747);
 * worst internal peak 1.096476 in this order against 334.39 reversed.
 *
 * Rows are [b0, b1, b2, -a1, -a2] for the transposed direct-form II
 * recurrence, not SciPy's [b0, b1, b2, a0, a1, a2].  Storage is X data
 * space to match the biquad primitive's coefficient fetch, as the H2
 * probe's header does; the probe never mutates them.
 */

#define ASRC_FULL_IIR_SOS              (6u)
#define ASRC_FULL_IIR_DF2T_SOS_CRC32   (0x67AE5F41u) /* LE float32 */
#define ASRC_FULL_IIR_MAX_ABS_COEFF    (1.767636657f)

static float asrc_full_iir_df2t_sos[ ASRC_FULL_IIR_SOS * 5u ] __attribute__((space(xmemory))) = {
    +0.0075237280565196166f, +0.01481801154015893f, +0.0075237280565196149f, +0.89601598922046999f, -0.27844524237466012f,   /* section 0, pole radius 0.527679109 */
    +1.0f, +1.7676366040703004f, +0.99999999999999978f, +0.37349220481721218f, -0.48519569793054851f,   /* section 1, pole radius 0.696559903 */
    +1.0f, +1.5104655709908688f, +0.99999999999999956f, -0.1521801778664115f, -0.69506200515688366f,   /* section 2, pole radius 0.833703787 */
    +1.0f, +1.3066154206839757f, +1.0f, -0.49017906917434279f, -0.83425831485679935f,   /* section 3, pole radius 0.913377422 */
    +1.0f, +1.1807799469172371f, +0.99999999999999978f, -0.67579907748635082f, -0.91908716412633396f,   /* section 4, pole radius 0.958690338 */
    +1.0f, +1.1230527482805941f, +0.99999999999999989f, -0.76340256006213458f, -0.9756450942587811f,   /* section 5, pole radius 0.987747485 */
};

#endif /* ASRC_FULL_IIR_PRECHECK_COEFFS_H */
