#ifndef ASRC_FULL_IIR_48_TO_32_COEFFS_H
#define ASRC_FULL_IIR_48_TO_32_COEFFS_H

/*
 * GENERATED by tools/asrc/gen_full_iir_integration_coeffs.py -- do not hand-edit.
 *
 * The 48 -> 32 kHz TRIAL anti-alias LPF that the A->B audio path links when
 * APP_ASRC_FULL_IIR_48_TO_32 is 1 and Full-IIR mode is selected at runtime:
 *
 *   elliptic order 12, 6 SOS, fp = 15 kHz,
 *   rp = 0.25 dB, rs = 120 dB, at 48 kHz input,
 *   with a fixed -1.5000 dB headroom gain folded into section 0.
 *
 * Topology: 48 kHz -> this IIR -> unchanged generic ASRC at step 1.5 -> 32 kHz.
 *
 * THE GAIN IS IN THE COEFFICIENTS ON PURPOSE.  It has to precede everything
 * that can clip, and the earliest such thing is section 0's own state (d1/d2
 * hold b1*x and b2*x).  Folding it into b0/b1/b2 of section 0 scales every
 * section's state and the output by the same constant and costs no
 * instructions.  So the response is EXACTLY this gain times the unity-gain
 * response, and separating the two in the report is a subtraction of a build
 * constant rather than a second measurement.
 *
 * COEFFICIENT IDENTITY.  The unity-gain table this is derived from has
 * CRC32 0x67AE5F41 -- the identity the Phase-2/3/4 benches and the *ai
 * probe were measured with (asrc_full_iir_precheck_coeffs.h).  The generator
 * refuses to emit if that no longer holds.
 *
 * SECTION ORDER IS MANDATORY.  Rows are low-Q-first (pole radii
 * 0.527679 < 0.696560 < 0.833704 < 0.913377 < 0.958690 < 0.987747);
 * worst internal peak 1.096476 (unity gain) in this order against 334.39
 * reversed.
 *
 * Rows are [b0, b1, b2, -a1, -a2] for the transposed direct-form II
 * recurrence, not SciPy's [b0, b1, b2, a0, a1, a2].  X data space, to match
 * the biquad primitive's coefficient fetch.
 */

#define ASRC_FULL_IIR_48_TO_32_SOS            (6u)
#define ASRC_FULL_IIR_48_TO_32_CRC32          (0xC006F014u) /* LE float32, gain folded */
#define ASRC_FULL_IIR_48_TO_32_UNITY_CRC32    (0x67AE5F41u) /* before the gain */
#define ASRC_FULL_IIR_48_TO_32_HEADROOM_GAIN  (+0.84139513969421387f)
#define ASRC_FULL_IIR_48_TO_32_HEADROOM_MDB   (-1500) /* dB x1000 */
#define ASRC_FULL_IIR_48_TO_32_MAX_ABS_COEFF  (1.767636657f)

/* Peaks the unity-gain filter reached, x full scale.  Multiply by the gain
 * above for what this table is expected to reach. */
#define ASRC_FULL_IIR_48_TO_32_UNITY_PEAK_HOST_MILLI   (1096u)
#define ASRC_FULL_IIR_48_TO_32_UNITY_PEAK_TARGET_MILLI (1118u)

static float asrc_full_iir_48_to_32_df2t_sos[ ASRC_FULL_IIR_48_TO_32_SOS * 5u ] __attribute__((space(xmemory))) = {
    +0.0063304282191365994f, +0.012467802889822497f, +0.0063304282191365977f, +0.89601598922046999f, -0.27844524237466012f,   /* section 0, pole radius 0.527679109  (gain folded here) */
    +1.0f, +1.7676366040703004f, +0.99999999999999978f, +0.37349220481721218f, -0.48519569793054851f,   /* section 1, pole radius 0.696559903 */
    +1.0f, +1.5104655709908688f, +0.99999999999999956f, -0.1521801778664115f, -0.69506200515688366f,   /* section 2, pole radius 0.833703787 */
    +1.0f, +1.3066154206839757f, +1.0f, -0.49017906917434279f, -0.83425831485679935f,   /* section 3, pole radius 0.913377422 */
    +1.0f, +1.1807799469172371f, +0.99999999999999978f, -0.67579907748635082f, -0.91908716412633396f,   /* section 4, pole radius 0.958690338 */
    +1.0f, +1.1230527482805941f, +0.99999999999999989f, -0.76340256006213458f, -0.9756450942587811f,   /* section 5, pole radius 0.987747485 */
};

#endif /* ASRC_FULL_IIR_48_TO_32_COEFFS_H */
