// audio_app_meas_tones.h -- GENERATED by tools/asrc/gen_asrc_meas_tones.py; regenerate there
#ifndef AUDIO_APP_MEAS_TONES_H
#define AUDIO_APP_MEAS_TONES_H

#include <stdint.h>
#include "app_specific_config_defs.h"

#if APP_ASRC_MEAS
// Nominal A-domain sample rate and tones these tables were generated against. The tables are
// SAMPLE-DOMAIN exact (cycles whole periods over `len` source-domain samples), NOT an absolute-
// time frequency reference (see tools/asrc/gen_asrc_meas_tones.py header).  So each row's tone_hz holds only at
// its own nominal_fs_hz: f = fs_source * cycles / len.
#define MEAS_TABLE_NOMINAL_FS_HZ   48000
#define MEAS_TABLE_TONE_LOW_HZ     1000
#define MEAS_TABLE_TONE_HIGH_HZ    18000
#define MEAS_TABLE_N_LEVELS        6
#define MEAS_TABLE_N_TONES         28

// Tone ROW indices.  LOW and HIGH_48 are the historical `tone_high` 0/1.  HIGH_96 exists
// because the HIGH_48 row lands at 36 kHz on a 96 kHz leg -- above a 48 kHz output's Nyquist,
// so it would alias instead of stressing the band edge.  Same absolute 18 kHz, 2x oversampled.
// Callers select a row per LIVE source rate (audio_app_meas_set_tone_high does that); this
// header only publishes the data.
#define MEAS_TONE_ROW_LOW          (0u)
#define MEAS_TONE_ROW_HIGH_48      (1u)
#define MEAS_TONE_ROW_HIGH_96      (2u)
#define MEAS_TABLE_HIGH96_FS_HZ    96000

// Sweep rows for the 48 -> 32 kHz N=97 audio-mode alias study.  The bench selects one
// with `*at 04 VV`, VV = the row index below as two hex digits.  Each row is
// sample-domain exact at 48 kHz; f = 48000 * cycles / len.
#define MEAS_TONE_ROW_SW_5000    ( 3u)   //  5000 Hz at 48000 Hz   len=48  cycles=5
#define MEAS_TONE_ROW_SW_10000   ( 4u)   // 10000 Hz at 48000 Hz   len=24  cycles=5
#define MEAS_TONE_ROW_SW_12000   ( 5u)   // 12000 Hz at 48000 Hz   len=4   cycles=1
#define MEAS_TONE_ROW_SW_13000   ( 6u)   // 13000 Hz at 48000 Hz   len=48  cycles=13
#define MEAS_TONE_ROW_SW_13500   ( 7u)   // 13500 Hz at 48000 Hz   len=32  cycles=9
#define MEAS_TONE_ROW_SW_14000   ( 8u)   // 14000 Hz at 48000 Hz   len=24  cycles=7
#define MEAS_TONE_ROW_SW_15000   ( 9u)   // 15000 Hz at 48000 Hz   len=16  cycles=5
#define MEAS_TONE_ROW_SW_15500   (10u)   // 15500 Hz at 48000 Hz   len=96  cycles=31
#define MEAS_TONE_ROW_SW_16000   (11u)   // 16000 Hz at 48000 Hz   len=3   cycles=1
#define MEAS_TONE_ROW_SW_16250   (12u)   // 16250 Hz at 48000 Hz   len=192 cycles=65
#define MEAS_TONE_ROW_SW_16500   (13u)   // 16500 Hz at 48000 Hz   len=32  cycles=11
#define MEAS_TONE_ROW_SW_16750   (14u)   // 16750 Hz at 48000 Hz   len=192 cycles=67
#define MEAS_TONE_ROW_SW_17000   (15u)   // 17000 Hz at 48000 Hz   len=48  cycles=17
#define MEAS_TONE_ROW_SW_17250   (16u)   // 17250 Hz at 48000 Hz   len=64  cycles=23
#define MEAS_TONE_ROW_SW_17500   (17u)   // 17500 Hz at 48000 Hz   len=96  cycles=35
#define MEAS_TONE_ROW_SW_17750   (18u)   // 17750 Hz at 48000 Hz   len=192 cycles=71
#define MEAS_TONE_ROW_SW_18250   (19u)   // 18250 Hz at 48000 Hz   len=192 cycles=73
#define MEAS_TONE_ROW_SW_18500   (20u)   // 18500 Hz at 48000 Hz   len=96  cycles=37
#define MEAS_TONE_ROW_SW_18750   (21u)   // 18750 Hz at 48000 Hz   len=64  cycles=25
#define MEAS_TONE_ROW_SW_19000   (22u)   // 19000 Hz at 48000 Hz   len=48  cycles=19
#define MEAS_TONE_ROW_SW_20000   (23u)   // 20000 Hz at 48000 Hz   len=12  cycles=5
#define MEAS_TONE_ROW_SW_21000   (24u)   // 21000 Hz at 48000 Hz   len=16  cycles=7
#define MEAS_TONE_ROW_SW_22000   (25u)   // 22000 Hz at 48000 Hz   len=24  cycles=11
#define MEAS_TONE_ROW_SW_23000   (26u)   // 23000 Hz at 48000 Hz   len=48  cycles=23
#define MEAS_TONE_ROW_SW_23900   (27u)   // 23900 Hz at 48000 Hz   len=480 cycles=239

typedef struct {
    const int32_t *samp;         // int24 samples (sign-extended in int32)
    uint16_t       len;          // samples per table (one full cycles-period block)
    uint16_t       cycles;       // whole sine periods in len
    int16_t        level_dbfs;
    uint32_t       tone_hz;      // nominal tone, valid at nominal_fs_hz
    uint32_t       nominal_fs_hz; // source rate tone_hz refers to
} meas_tone_table_t;

// tone_row: 0..MEAS_TABLE_N_TONES-1 (see MEAS_TONE_ROW_* above); out-of-range falls back to
// row 0. level_idx 0..5 = {-1,-60,-20,-40,-80,-6} dBFS.
const meas_tone_table_t *audio_app_meas_table( uint8_t tone_row, uint8_t level_idx );
#endif // APP_ASRC_MEAS

#endif // AUDIO_APP_MEAS_TONES_H
