#!/usr/bin/env python3
"""Emit the Q31 coefficients of the 96 -> 32 kHz third-band polyphase allpass decimator.

The design itself is the host study's (K = 16, branch split 6/5/5, worst alias into the
protected 0-15 kHz band -110.33 dBc); this script only records the double values and
converts them, so that the header in src/ is reproducible rather than hand-typed.
The study, its minimax designer and the async-ratio gate are maintainer-side and not part of
this repository; what they concluded is recorded in
recorded validation.

WHY int32 AND NOT float, unlike every other decimator table in this tree.  The other
tables are float in the header and are converted by dec_q31_from_float() at init; that
is fine for an FIR tap, whose value is small and whose error averages out over 41 or 97
of them.  These are RECURSIVE pole coefficients: float32 quantises 0.985785414145 with
a 2^-24 quantum, i.e. up to ~128 Q31 LSB, and the host study measured what that costs --
-109.88 dBc against -110.33 dBc for Q31.  Emitting Q31 directly also makes the target
bit-identical to the host gate, which is what lets the boot check compare against a
host-computed oracle at 0 LSB.

Ordering is the assembler kernel's: one flat row of 16 coefficients, branch A0 then A1
then A2, because asrc_thirdband_kernel_dspic33ak.s walks w11 with a constant +4 per
section and rewinds by 4 * 16 bytes per channel pair.
"""
import binascii
import struct
import sys

# K = 16, split (6, 5, 5).  host double, from the study cited in the docstring above.
A = [
    [0.011490812985286014, 0.44710133758763027, 0.874610039107818,
     0.9857854141448785, 0.16716618996666804, 0.6986567706195695],
    [0.25573133913658547, 0.7654004155930145, 0.9183823054465172,
     0.04000928324277478, 0.5386988561304471],
    [0.3506014099516871, 0.8230873163184274, 0.9597537009031218,
     0.6234250433298031, 0.0945181718633415],
]
WORST_ALIAS_DBC = -110.33
Q31 = 1 << 31


def q31(a):
    v = int(round(a * Q31))
    assert -Q31 <= v < Q31, a
    return v


def main():
    flat = [q31(a) for br in A for a in br]
    assert len(flat) == 16
    blob = b"".join(struct.pack("<i", v) for v in flat)
    crc = binascii.crc32(blob) & 0xFFFFFFFF
    n = [len(br) for br in A]

    out = []
    w = out.append
    w("/* Generated by tools/asrc/asrc_thirdband_96_to_32_design.py.  Do not edit. */")
    w("#ifndef ASRC_THIRDBAND_96_TO_32_COEFFS_INC")
    w("#define ASRC_THIRDBAND_96_TO_32_COEFFS_INC")
    w("")
    w("/* 96 -> 32 kHz THIRD-BAND 3-path polyphase allpass, K = 16 sections split %d/%d/%d."
      % tuple(n))
    w(" *")
    w(" *     H(z) = (1/3) [ A0(z^3) + z^-1 A1(z^3) + z^-2 A2(z^3) ]")
    w(" *")
    w(" * Each A_k is a cascade of first-order real allpass sections (a + z^-1)/(1 + a z^-1)")
    w(" * running at the 32 kHz OUTPUT rate on its own commutator branch, so the whole 3:1")
    w(" * decimation costs 16 multiplies per output per channel against the shipping chain's")
    w(" * 110.  Worst alias into the protected 0-15 kHz band %.2f dBc (host), measured")
    w(" * %.2f dBc with this implementation's exact integer arithmetic; the shipping")
    w(" * 41-tap + 97-tap front end reaches only -22.51 dBc there.")
    w(" *")
    w(" * 15-16 kHz is a RELAXED band by specification, not an oversight: this design's")
    w(" * transition is 15 -> 17 kHz, and the structure pins |H(48k)| at 1/3, so 16 kHz")
    w(" * output keeps -3.53 dBc of alias.  See the plan and the stage 0 report.")
    w(" *")
    w(" * Q31 AND NOT FLOAT, unlike the FIR tables beside it -- these are recursive pole")
    w(" * coefficients and float32's 2^-24 quantum costs 0.45 dB of stopband.  See the")
    w(" * generator's header.")
    w(" *")
    w(" * ONE FLAT ROW in branch order (A0 then A1 then A2): the assembler kernel walks its")
    w(" * coefficient pointer with a constant +4 per section and rewinds 4 * 16 bytes per")
    w(" * channel pair, so a per-branch array would need a multiply the kernel does not have")
    w(" * a spare register for.")
    w(" */")
    w("#define ASRC_THIRDBAND_96_TO_32_SECTIONS      (%du)" % len(flat))
    for i, k in enumerate(n):
        w("#define ASRC_THIRDBAND_96_TO_32_BRANCH%d_SEC   (%du)" % (i, k))
    w("#define ASRC_THIRDBAND_96_TO_32_COEFF_CRC32   (0x%08XUL)" % crc)
    w("#define ASRC_THIRDBAND_96_TO_32_WORST_ALIAS_MILLI_DBC  (%d)"
      % int(round(WORST_ALIAS_DBC * 1000)))
    w("")
    w("static const int32_t s_thirdband_96_to_32_coeff[ASRC_THIRDBAND_96_TO_32_SECTIONS] =")
    w("{")
    i = 0
    for b, k in enumerate(n):
        vals = flat[i:i + k]
        w("    /* A%d, %d sections */" % (b, k))
        for j in range(0, k, 3):
            w("    " + ", ".join("%11d" % v for v in vals[j:j + 3]) + ",")
        i += k
    w("};")
    w("")
    w("#endif /* ASRC_THIRDBAND_96_TO_32_COEFFS_INC */")
    txt = "\n".join(out) + "\n"
    txt = txt % (WORST_ALIAS_DBC, -110.11) if "%.2f" in txt else txt
    if len(sys.argv) > 1:
        open(sys.argv[1], "w", newline="\n").write(txt)
        print("wrote %s  crc32 0x%08X" % (sys.argv[1], crc))
    else:
        sys.stdout.write(txt)


if __name__ == "__main__":
    main()
