#!/usr/bin/env python3
"""Generate and verify the MEAS clean-tone tables (audio_app_meas_tones.{h,c}).

RECREATED 2026-08-02.  Both generated files carried a `GENERATED by
tools/gen_asrc_meas_tones.py` header line, but no such script existed anywhere in
the project, so the tables were effectively unmaintainable: adding the 96 kHz-source
HF row needed the generator back first.  This is that generator, reconstructed by solving the
existing tables for their quantisation rule and then required to reproduce every
pre-existing sample byte-for-byte (`--check-legacy`).  The output path in the
generated headers is updated to this file's real location.

WHY A TABLE AND NOT A RUNTIME SINE.  audio_app_meas.c's header records it: a
runtime sinf/float-phase/lrintf source measured a ~-109 dB THD+N floor, which
would cap kernel measurement well short of the -120/-123 dB targets.  A
precomputed table advanced once per SOURCE-domain frame has no such floor.

SAMPLE-DOMAIN EXACT, NOT ABSOLUTE-FREQUENCY.  Each table holds `cycles` whole
sine periods over `len` samples, so it is perfectly periodic (no phase-accumulator
truncation, no spectral leakage from a partial cycle) but its frequency follows
the rate it is played at:

    f = fs_source * cycles / len

That is why a 96 kHz leg needs its own HF row.  The 48 kHz HIGH table is 8
samples / 3 cycles = 18 kHz at 48 kHz, but 36 kHz at 96 kHz -- above a 48 kHz
leg's output Nyquist, where it would alias and measure nothing meaningful.  The
96 kHz HF row is the same absolute tone at 2x oversampling: 16 samples /
3 cycles = 18 kHz at 96 kHz.  Both are minimal (gcd(len, cycles) == 1); a longer
table would be redundant, not more accurate.

QUANTISATION.  Solved from the shipped tables and asserted by --check-legacy:

    A       = (2**23 - 1) * 10**(level_dbfs / 20)
    samp[k] = floor( A * sin(2*pi*cycles*k/len) + 0.5 )

Note the full scale is 2**23 - 1, NOT 2**23: with 2**23 the -1 dBFS peak rounds
to 7476355 where the shipped table has 7476354.  Getting this wrong reproduces
most samples and silently differs on the few near a peak.

No third-party dependency (the standard library is enough for exact integers).
"""

from __future__ import annotations

import argparse
import math
import pathlib
import sys


ROOT = pathlib.Path(__file__).resolve().parents[2]
HEADER_OUTPUT = ROOT / "src/app/apps/asrc/audio_app_meas_tones.h"
SOURCE_OUTPUT = ROOT / "src/app/apps/asrc/audio_app_meas_tones.c"
SELF_PATH = "tools/asrc/gen_asrc_meas_tones.py"

FULL_SCALE = (2 ** 23) - 1

# *at 02 VV index order -- deliberately not sorted; index 0 is the THD+N stimulus and
# index 1 the DR stimulus, so the two most-used levels are the two lowest indices.
LEVELS_DBFS = (-1, -60, -20, -40, -80, -6)

# One entry per tone ROW, in table order.  (name, len, cycles, nominal_fs_hz)
# nominal_fs_hz is the source rate at which this row's tone_hz holds; the row is
# still perfectly periodic at any other rate, just at a different frequency.
ROWS = (
    ("LOW",     48,  1, 48000),   # 1 kHz at 48 kHz  (2 kHz at 96 kHz)
    ("HIGH_48",  8,  3, 48000),   # 18 kHz at 48 kHz (36 kHz at 96 kHz -- unusable there)
    ("HIGH_96", 16,  3, 96000),   # 18 kHz at 96 kHz (9 kHz at 48 kHz)
    # Sweep rows -- ADDED 2026-08-23 for the 48 -> 32 kHz N=97 audio-mode hardware alias
    # study (recorded validation).
    # MEASUREMENT DATA ONLY: this file and its outputs are wholly inside #if APP_ASRC_MEAS,
    # so a product build (APP_ASRC_MEAS=0) compiles none of it.  Rows 0..2 keep their indices
    # and their samples (--check-legacy still passes), so every earlier measurement stays valid.
    # 18 kHz is deliberately NOT repeated here -- it is row 1 (HIGH_48).
    ("SW_5000",   48,   5, 48000),   # 5 kHz at 48 kHz
    ("SW_10000",  24,   5, 48000),   # 10 kHz at 48 kHz
    ("SW_12000",   4,   1, 48000),   # 12 kHz at 48 kHz
    ("SW_13000",  48,  13, 48000),   # 13 kHz at 48 kHz
    ("SW_13500",  32,   9, 48000),   # 13.5 kHz at 48 kHz
    ("SW_14000",  24,   7, 48000),   # 14 kHz at 48 kHz
    ("SW_15000",  16,   5, 48000),   # 15 kHz at 48 kHz
    ("SW_15500",  96,  31, 48000),   # 15.5 kHz at 48 kHz
    ("SW_16000",   3,   1, 48000),   # 16 kHz at 48 kHz
    ("SW_16250", 192,  65, 48000),   # 16.25 kHz at 48 kHz
    ("SW_16500",  32,  11, 48000),   # 16.5 kHz at 48 kHz
    ("SW_16750", 192,  67, 48000),   # 16.75 kHz at 48 kHz
    ("SW_17000",  48,  17, 48000),   # 17 kHz at 48 kHz
    ("SW_17250",  64,  23, 48000),   # 17.25 kHz at 48 kHz
    ("SW_17500",  96,  35, 48000),   # 17.5 kHz at 48 kHz
    ("SW_17750", 192,  71, 48000),   # 17.75 kHz at 48 kHz
    ("SW_18250", 192,  73, 48000),   # 18.25 kHz at 48 kHz
    ("SW_18500",  96,  37, 48000),   # 18.5 kHz at 48 kHz
    ("SW_18750",  64,  25, 48000),   # 18.75 kHz at 48 kHz
    ("SW_19000",  48,  19, 48000),   # 19 kHz at 48 kHz
    ("SW_20000",  12,   5, 48000),   # 20 kHz at 48 kHz
    ("SW_21000",  16,   7, 48000),   # 21 kHz at 48 kHz
    ("SW_22000",  24,  11, 48000),   # 22 kHz at 48 kHz
    ("SW_23000",  48,  23, 48000),   # 23 kHz at 48 kHz
    ("SW_23900", 480, 239, 48000),   # 23.9 kHz at 48 kHz
)

# Rows 0 and 1 predate this generator.  --check-legacy pins their samples to the
# values that were in the tree at commit 8f7d76e, so a quantisation regression in
# this script cannot silently invalidate every measurement taken before today.
LEGACY_ROWS = 2

# Rows below this index are the historical named rows (LOW / HIGH_48 / HIGH_96).
LEGACY_SWEEP_BASE = 3


def tone_hz(length: int, cycles: int, fs_hz: int) -> int:
    """Exact tone frequency; integer by construction for every row here."""
    num = fs_hz * cycles
    if num % length != 0:
        raise ValueError(f"non-integer tone: fs={fs_hz} cycles={cycles} len={length}")
    return num // length


def quantise(length: int, cycles: int, level_dbfs: int) -> list[int]:
    amp = FULL_SCALE * (10.0 ** (level_dbfs / 20.0))
    return [
        int(math.floor(amp * math.sin(2.0 * math.pi * cycles * k / length) + 0.5))
        for k in range(length)
    ]


def check_geometry() -> None:
    for name, length, cycles, fs_hz in ROWS:
        if math.gcd(length, cycles) != 1:
            raise ValueError(
                f"row {name}: len={length} cycles={cycles} is not minimal "
                f"(gcd={math.gcd(length, cycles)}); use len/gcd and cycles/gcd"
            )
        f = tone_hz(length, cycles, fs_hz)
        if f * 2 >= fs_hz:
            raise ValueError(f"row {name}: {f} Hz is at or above the {fs_hz} Hz source Nyquist")


def render_header() -> str:
    low = next(r for r in ROWS if r[0] == "LOW")
    high48 = next(r for r in ROWS if r[0] == "HIGH_48")
    high96 = next(r for r in ROWS if r[0] == "HIGH_96")
    lines: list[str] = []
    a = lines.append
    a(f"// audio_app_meas_tones.h -- GENERATED by {SELF_PATH}; regenerate there")
    a("#ifndef AUDIO_APP_MEAS_TONES_H")
    a("#define AUDIO_APP_MEAS_TONES_H")
    a("")
    a("#include <stdint.h>")
    a('#include "app_specific_config_defs.h"')
    a("")
    a("#if APP_ASRC_MEAS")
    a("// Nominal A-domain sample rate and tones these tables were generated against. The tables are")
    a("// SAMPLE-DOMAIN exact (cycles whole periods over `len` source-domain samples), NOT an absolute-")
    a(f"// time frequency reference (see {SELF_PATH} header).  So each row's tone_hz holds only at")
    a("// its own nominal_fs_hz: f = fs_source * cycles / len.")
    a(f"#define MEAS_TABLE_NOMINAL_FS_HZ   {low[3]}")
    a(f"#define MEAS_TABLE_TONE_LOW_HZ     {tone_hz(low[1], low[2], low[3])}")
    a(f"#define MEAS_TABLE_TONE_HIGH_HZ    {tone_hz(high48[1], high48[2], high48[3])}")
    a(f"#define MEAS_TABLE_N_LEVELS        {len(LEVELS_DBFS)}")
    a(f"#define MEAS_TABLE_N_TONES         {len(ROWS)}")
    a("")
    a("// Tone ROW indices.  LOW and HIGH_48 are the historical `tone_high` 0/1.  HIGH_96 exists")
    a("// because the HIGH_48 row lands at 36 kHz on a 96 kHz leg -- above a 48 kHz output's Nyquist,")
    a("// so it would alias instead of stressing the band edge.  Same absolute 18 kHz, 2x oversampled.")
    a("// Callers select a row per LIVE source rate (audio_app_meas_set_tone_high does that); this")
    a("// header only publishes the data.")
    a("#define MEAS_TONE_ROW_LOW          (0u)")
    a("#define MEAS_TONE_ROW_HIGH_48      (1u)")
    a("#define MEAS_TONE_ROW_HIGH_96      (2u)")
    a(f"#define MEAS_TABLE_HIGH96_FS_HZ    {high96[3]}")
    if len(ROWS) > LEGACY_SWEEP_BASE:
        a("")
        a("// Sweep rows for the 48 -> 32 kHz N=97 audio-mode alias study.  The bench selects one")
        a("// with `*at 04 VV`, VV = the row index below as two hex digits.  Each row is")
        a("// sample-domain exact at 48 kHz; f = 48000 * cycles / len.")
        for row_idx, (name, length, cycles, fs_hz) in enumerate(ROWS):
            if row_idx < LEGACY_SWEEP_BASE:
                continue
            a("#define MEAS_TONE_ROW_%-8s   (%2uu)   // %5u Hz at %u Hz   len=%-3u cycles=%u"
              % (name, row_idx, tone_hz(length, cycles, fs_hz), fs_hz, length, cycles))
    a("")
    a("typedef struct {")
    a("    const int32_t *samp;         // int24 samples (sign-extended in int32)")
    a("    uint16_t       len;          // samples per table (one full cycles-period block)")
    a("    uint16_t       cycles;       // whole sine periods in len")
    a("    int16_t        level_dbfs;")
    a("    uint32_t       tone_hz;      // nominal tone, valid at nominal_fs_hz")
    a("    uint32_t       nominal_fs_hz; // source rate tone_hz refers to")
    a("} meas_tone_table_t;")
    a("")
    a("// tone_row: 0..MEAS_TABLE_N_TONES-1 (see MEAS_TONE_ROW_* above); out-of-range falls back to")
    a("// row 0. level_idx 0..5 = {-1,-60,-20,-40,-80,-6} dBFS.")
    a("const meas_tone_table_t *audio_app_meas_table( uint8_t tone_row, uint8_t level_idx );")
    a("#endif // APP_ASRC_MEAS")
    a("")
    a("#endif // AUDIO_APP_MEAS_TONES_H")
    a("")
    return "\n".join(lines)


def render_source() -> str:
    lines: list[str] = []
    a = lines.append
    a(f"// audio_app_meas_tones.c -- GENERATED by {SELF_PATH}; regenerate there")
    a('#include "audio_app_meas_tones.h"')
    a("")
    a("#if !SONORA_APP_IS_ASRC")
    a('#  error "audio_app_meas_tones.c is ASRC-app-owned; build it only in an ASRC manifest '
      '(SONORA_APP_IS_ASRC). Check nbproject/configurations.xml source exclusions."')
    a("#endif")
    a("")
    a("#if APP_ASRC_MEAS")
    a("")
    a("// Stale-table guard: regenerate if the MEAS nominal rate / tones change.")
    a("_Static_assert( (int)APP_MEAS_FS_A_HZ == MEAS_TABLE_NOMINAL_FS_HZ,")
    a('                "MEAS tone tables stale: APP_MEAS_FS_A_HZ != table nominal fs; regenerate" );')
    a("_Static_assert( (int)APP_MEAS_TONE_LOW_HZ == MEAS_TABLE_TONE_LOW_HZ,")
    a('                "MEAS tone tables stale: low tone changed; regenerate" );')
    a("_Static_assert( (int)APP_MEAS_TONE_HIGH_HZ == MEAS_TABLE_TONE_HIGH_HZ,")
    a('                "MEAS tone tables stale: high tone changed; regenerate" );')
    a("")
    for row_idx, (_name, length, cycles, fs_hz) in enumerate(ROWS):
        f_hz = tone_hz(length, cycles, fs_hz)
        for lvl_idx, level in enumerate(LEVELS_DBFS):
            samples = quantise(length, cycles, level)
            body = ", ".join(str(v) for v in samples)
            a(f"static const int32_t tbl_t{row_idx}_l{lvl_idx}[{length}] = {{ {body} }};"
              f"  // tone={f_hz}Hz level={level}dBFS cycles={cycles} fs={fs_hz}Hz")
    a("")
    a(f"static const meas_tone_table_t k_tables[{len(ROWS)}][{len(LEVELS_DBFS)}] = {{")
    for row_idx, (name, length, cycles, fs_hz) in enumerate(ROWS):
        f_hz = tone_hz(length, cycles, fs_hz)
        entries = ", ".join(
            f"{{ tbl_t{row_idx}_l{lvl_idx}, {length}u, {cycles}u, {level}, {f_hz}u, {fs_hz}u }}"
            for lvl_idx, level in enumerate(LEVELS_DBFS)
        )
        a(f"    {{ {entries} }},  // tone {name}")
    a("};")
    a("")
    a("const meas_tone_table_t *audio_app_meas_table( uint8_t tone_row, uint8_t level_idx )")
    a("{")
    a(f"    if( tone_row >= {len(ROWS)}u )  {{ tone_row = 0u; }}")
    a(f"    if( level_idx >= {len(LEVELS_DBFS)}u ) {{ level_idx = 0u; }}")
    a("    return &k_tables[tone_row][level_idx];")
    a("}")
    a("")
    a("#endif // APP_ASRC_MEAS")
    a("")
    return "\n".join(lines)


# Samples of the two pre-existing rows, transcribed from the tree at commit 8f7d76e.
# Only the extremes of each row are pinned per level plus the full -1 dBFS vector: enough
# that a wrong full-scale constant, a wrong rounding mode or a wrong level formula all fail,
# without duplicating 300 numbers.  A byte-level regeneration diff is the other half of the
# gate (run --write on a clean tree and `git diff` the two data blocks).
LEGACY_PIN = {
    (0, 0): [0, 975860, 1935023, 2861077, 3738177, 4551316, 5286581, 5931390, 6474712,
             6907250, 7221603, 7412393, 7476354],
    (0, 1): [0, 1095, 2171, 3210, 4194, 5107, 5932, 6655, 7265, 7750, 8103, 8317, 8389],
    (0, 2): [0, 109493, 217113, 321018, 419430, 510666, 593164, 665513, 726475, 775006,
             810277, 831684, 838861],
    (0, 3): [0, 10949, 21711, 32102, 41943, 51067, 59316, 66551, 72647, 77501, 81028,
             83168, 83886],
    (0, 4): [0, 109, 217, 321, 419, 511, 593, 666, 726, 775, 810, 832, 839],
    (0, 5): [0, 548766, 1088143, 1608902, 2102131, 2559393, 2972863, 3335466, 3640998,
             3884232, 4061006, 4168295, 4204263],
    (1, 0): [0, 5286581, -7476354, 5286581, 0, -5286581, 7476354, -5286581],
    (1, 1): [0, 5932, -8389, 5932, 0, -5932, 8389, -5932],
    (1, 2): [0, 593164, -838861, 593164, 0, -593164, 838861, -593164],
    (1, 3): [0, 59316, -83886, 59316, 0, -59316, 83886, -59316],
    (1, 4): [0, 593, -839, 593, 0, -593, 839, -593],
    (1, 5): [0, 2972863, -4204263, 2972863, 0, -2972863, 4204263, -2972863],
}


def check_legacy() -> int:
    bad = 0
    for (row_idx, lvl_idx), want in sorted(LEGACY_PIN.items()):
        name, length, cycles, _fs = ROWS[row_idx]
        got = quantise(length, cycles, LEVELS_DBFS[lvl_idx])[: len(want)]
        if got != want:
            bad += 1
            diff = [(k, g, w) for k, (g, w) in enumerate(zip(got, want)) if g != w]
            print(f"ERROR: row {name} level {LEVELS_DBFS[lvl_idx]} dBFS differs from the "
                  f"shipped table at {diff[:4]}", file=sys.stderr)
    if bad == 0:
        print(f"legacy tables reproduced exactly ({len(LEGACY_PIN)} vectors, "
              f"{LEGACY_ROWS} pre-existing rows)")
    return 1 if bad else 0


def print_survey() -> None:
    print(f"full scale = {FULL_SCALE} (2**23 - 1)")
    print(f"{'row':<9} {'len':>4} {'cyc':>4} {'nom fs':>8} {'tone':>7}   f at 48 kHz / 96 kHz")
    for name, length, cycles, fs_hz in ROWS:
        f48 = 48000 * cycles / length
        f96 = 96000 * cycles / length
        print(f"{name:<9} {length:>4} {cycles:>4} {fs_hz:>8} {tone_hz(length, cycles, fs_hz):>7}"
              f"   {f48:>9.1f} / {f96:>9.1f}")
    print()
    print("Usability, output Nyquist in brackets:")
    print("  96 k -> 48 k [24000]: LOW 2000 ok, HIGH_48 36000 ALIASES, HIGH_96 18000 ok")
    print("  48 k -> 96 k [48000]: LOW 1000 ok, HIGH_48 18000 ok,      HIGH_96  9000 ok")
    print("  96 k -> 16 k  [8000]: LOW 2000 ok, HIGH_* both above Nyquist -> stopband test only")


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="write the generated C files")
    mode.add_argument("--check", action="store_true", help="fail if the generated files are stale")
    mode.add_argument("--check-legacy", action="store_true",
                      help="fail unless the two pre-existing tone rows reproduce exactly")
    args = parser.parse_args()

    check_geometry()

    if args.check_legacy:
        return check_legacy()

    expected_header = render_header()
    expected_source = render_source()

    if args.write:
        # Match the checkout format (see .gitattributes: * text=auto eol=crlf) so --write
        # does not leave the tree content-clean but diff-dirty.
        HEADER_OUTPUT.write_text(expected_header, encoding="ascii", newline="\r\n")
        SOURCE_OUTPUT.write_text(expected_source, encoding="ascii", newline="\r\n")
        print(f"wrote {HEADER_OUTPUT.relative_to(ROOT)}")
        print(f"wrote {SOURCE_OUTPUT.relative_to(ROOT)}")
        return 0

    if args.check:
        rc = 0
        for path, expected in ((HEADER_OUTPUT, expected_header), (SOURCE_OUTPUT, expected_source)):
            actual = path.read_text(encoding="ascii").replace("\r\n", "\n")
            if actual != expected:
                print(f"ERROR: stale generated file: {path.relative_to(ROOT)}", file=sys.stderr)
                rc = 1
        if rc == 0:
            print("generated MEAS tone tables are up to date")
        return rc

    print_survey()
    return check_legacy()


if __name__ == "__main__":
    raise SystemExit(main())
