#!/usr/bin/env python3
"""Emit the Phase-4 six-SOS full-IIR candidate as a DF2T coefficient header.

The candidate is NOT retyped from the Phase-4 report.  It is re-derived from the
design specification and then required to match the Phase-4 machine-readable
record bit-for-bit in float64, so the header cannot silently drift from the
qualified filter:

    scipy.signal.ellip(12, 0.25, 120, 15000/24000, 'low', output='sos')
    -> the Phase-1 study's normalize_sos_dc()

Section order is the file order, which the Phase-4 headroom sweep selected as
`default` == `low-Q-first` == [0,1,2,3,4,5] (worst internal peak 1.096476).
Reversing it is unsafe (334.39), so the order is emitted, not left to the caller.

The biquad library stores each section as [b0, b1, b2, -a1, -a2], which is NOT
SciPy's [b0, b1, b2, a0, a1, a2] row.  a0 is 1.0 for every row here and is
asserted rather than assumed.

Measurement-only: this header is consumed by the opt-in *af precheck bench and
by nothing in the shipping audio path.
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import pathlib
import struct
import sys
import zlib

import numpy as np
from scipy import signal

ROOT = pathlib.Path(__file__).resolve().parents[2]
PHASE1 = ROOT / "tools" / "asrc" / "asrc_48_to_32_hybrid_filter_study.py"
# The Phase-4 machine-readable record, kept in the repo so reproduction does not
# depend on a scratch directory outside it.
PHASE4_RECORD = ROOT / "tools" / "asrc" / "asrc_48_to_32_full_iir_feasibility_2026-09-05.json"

ORDER = 12
RIPPLE_DB = 0.25
STOP_DB = 120.0
PASS_HZ = 15_000.0
FS_IN = 48_000.0
SECTION_ORDER = (0, 1, 2, 3, 4, 5)


def load_phase1():
    spec = importlib.util.spec_from_file_location("full_iir_phase1", PHASE1)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {PHASE1}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def design_sos() -> np.ndarray:
    phase1 = load_phase1()
    raw = signal.ellip(ORDER, RIPPLE_DB, STOP_DB, PASS_HZ / (FS_IN / 2.0),
                       btype="low", output="sos")
    return phase1.normalize_sos_dc(np.asarray(raw, dtype=np.float64))


def df2t_rows(sos: np.ndarray) -> np.ndarray:
    rows = []
    for b0, b1, b2, a0, a1, a2 in sos[list(SECTION_ORDER)]:
        if a0 != 1.0:
            raise SystemExit(f"a0 must be 1.0 after normalisation, got {a0!r}")
        rows.append([b0, b1, b2, -a1, -a2])
    return np.asarray(rows, dtype=np.float64)


def c_float(value: float) -> str:
    """A C floating constant.  "%.17g" of 1.0 is "1", and "1f" is not a valid C
    token -- the suffix needs a fractional part or an exponent."""
    text = f"{value:+.17g}"
    if ("." not in text) and ("e" not in text) and ("E" not in text):
        text += ".0"
    return text + "f"


def crc32_le_f32(values: np.ndarray) -> int:
    packed = b"".join(struct.pack("<f", float(np.float32(v))) for v in values.ravel())
    return zlib.crc32(packed) & 0xFFFFFFFF


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=pathlib.Path,
                        default=ROOT / "src" / "app" / "apps" / "asrc" /
                                "asrc_full_iir_precheck_coeffs.h")
    parser.add_argument("--verify-json", type=pathlib.Path, default=PHASE4_RECORD,
                        help="Phase-4 record to compare the re-derived float64 SOS against")
    args = parser.parse_args()

    sos = design_sos()
    if args.verify_json is not None:
        record = json.loads(args.verify_json.read_text())
        reference = np.asarray(record["best"]["coefficients"]["sos_float64"], dtype=np.float64)
        delta = float(np.max(np.abs(sos - reference)))
        print(f"phase-4 record max|delta| = {delta:.3e}")
        if delta != 0.0:
            raise SystemExit("re-derived SOS does not match the Phase-4 record")

    rows = df2t_rows(sos)
    radii = [float(np.max(np.abs(np.roots(row[3:])))) for row in sos[list(SECTION_ORDER)]]
    if radii != sorted(radii):
        raise SystemExit(f"emitted order is not low-Q-first: {radii}")
    crc = crc32_le_f32(rows)
    max_abs = float(np.max(np.abs(rows.astype(np.float32))))

    lines = [
        "#ifndef ASRC_FULL_IIR_PRECHECK_COEFFS_H",
        "#define ASRC_FULL_IIR_PRECHECK_COEFFS_H",
        "",
        "/*",
        " * GENERATED by tools/asrc/gen_full_iir_precheck_coeffs.py -- do not hand-edit.",
        " *",
        " * Phase-4 full-IIR candidate, measurement-only:",
        " *",
        f" *   elliptic order {ORDER}, {len(rows)} SOS, fp = {PASS_HZ / 1000.0:g} kHz,",
        f" *   rp = {RIPPLE_DB} dB, rs = {STOP_DB:g} dB, at {FS_IN / 1000.0:g} kHz input.",
        " *",
        " * Topology it belongs to: 48 kHz -> this IIR -> unchanged generic ASRC at",
        " * step about 1.5 -> 32 kHz.  Host qualification (Phase 4): worst full-chain",
        " * alias -119.751 dBc over 0-15 kHz, wanted at 15 kHz +0.000031 dB.",
        " *",
        " * SECTION ORDER IS MANDATORY.  Rows are low-Q-first (pole radii",
        " * " + " < ".join(f"{r:.6f}" for r in radii) + ");",
        " * worst internal peak 1.096476 in this order against 334.39 reversed.",
        " *",
        " * Rows are [b0, b1, b2, -a1, -a2] for the transposed direct-form II",
        " * recurrence, not SciPy's [b0, b1, b2, a0, a1, a2].  Storage is X data",
        " * space to match the biquad primitive's coefficient fetch, as the H2",
        " * probe's header does; the probe never mutates them.",
        " */",
        "",
        f"#define ASRC_FULL_IIR_SOS              ({len(rows)}u)",
        f"#define ASRC_FULL_IIR_DF2T_SOS_CRC32   (0x{crc:08X}u) /* LE float32 */",
        f"#define ASRC_FULL_IIR_MAX_ABS_COEFF    ({max_abs:.9f}f)",
        "",
        "static float asrc_full_iir_df2t_sos[ ASRC_FULL_IIR_SOS * 5u ]"
        " __attribute__((space(xmemory))) = {",
    ]
    for index, row in enumerate(rows):
        body = ", ".join(c_float(value) for value in row)
        lines.append(f"    {body},   /* section {index}, pole radius {radii[index]:.9f} */")
    lines += [
        "};",
        "",
        "#endif /* ASRC_FULL_IIR_PRECHECK_COEFFS_H */",
        "",
    ]
    args.out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {args.out}")
    print(f"CRC32(LE float32) = 0x{crc:08X}   max|coeff| = {max_abs:.9f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
