//===========================================================
// audio_transport_sai_live.c
//
// Opt-in CMSIS-SAI wrapper LIVE-loopback verification harness.
// Moved verbatim out of main.c so the production audio path (audio_transport.c) stays clean.
// Owns the wrapper RX/TX block buffers, the phase-continuous test tone, the per-block
// instrumentation, the ARM_SAI event callback, the wrapper start sequence, and the
// loopback-localiser debug print. Inert unless the resolved live-test selection is true.
//===========================================================

#include "resolved_sai_test_config.h"
#include "app_runtime_overrides.h"

#if RESOLVED_SAI_TEST_LIVE_ENABLED

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <math.h>

#include "Driver_SAI_dsPIC33AK.h"   // Driver_SAI0 + ARM_SAI_* / ARM_DRIVER_* / ARM_SAI_EVENT_*
#include "audio_transport_sai_live.h"

#define SAI_LIVE_BLOCK_SAMPLES \
    ((uint32_t)RESOLVED_SAI_TEST_BLOCK_FRAMES * \
     (uint32_t)RESOLVED_SAI_TEST_SLOTS_PER_FRAME)

static int32_t g_sai_live_rx[SAI_LIVE_BLOCK_SAMPLES];
static int32_t g_sai_live_tx[SAI_LIVE_BLOCK_SAMPLES];

/* Observation-only instrumentation (no data-path change). Localises where a silent
 * loopback dies: rx/tx COMPLETE counts (copy-layer cycling?), and per-interval
 * abs-peak of the captured-input / sent-output blocks (real signal present?). Read
 * + reset in audio_transport_sai_live_dbg_print(). All updated only in ISR (event cb). */
static volatile uint32_t g_sai_live_rx_blk  = 0u;   /* RECEIVE_COMPLETE count */
static volatile uint32_t g_sai_live_tx_blk  = 0u;   /* SEND_COMPLETE count    */
static volatile uint32_t g_sai_live_rx_peak = 0u;   /* max |sample| in rx     */
static volatile uint32_t g_sai_live_tx_peak = 0u;   /* max |sample| in tx     */

static uint32_t local_sai_abspeak( const int32_t *b, uint32_t n )
{
    uint32_t pk = 0u;
    for( uint32_t i = 0u; i < n; i++ )
    {
        int32_t  v = b[i];
        uint32_t a = (v < 0) ? (uint32_t)(-(int64_t)v) : (uint32_t)v;
        if( a > pk ) { pk = a; }
    }
    return pk;
}

#if RESOLVED_SAI_TEST_TONE_ENABLED || RESOLVED_SAI_TEST_HYBRID_TX_ENABLED
/* Phase-continuous test tone on slots 0/1 (others silent), generated by a 2nd-order
 * resonator y[n]=coef*y[n-1]-y[n-2] (coef=2cos(w)); state persists across blocks =>
 * seamless, no per-sample sin() in the ISR. ~-6 dBFS (24-bit aligned). */
#define SAI_TONE_HZ      (800.0)
#define SAI_TONE_AMP     (1073741824.0)   /* 0x40000000 ~ -6 dBFS */
#define SAI_TONE_TWO_PI  (6.283185307179586)

static double g_sai_tone_coef = 0.0;      /* 2*cos(w)  */
static double g_sai_tone_y1   = 0.0;      /* y[n-1]    */
static double g_sai_tone_y2   = 0.0;      /* y[n-2]    */

static void local_sai_tone_init( void )
{
    const double w = (SAI_TONE_TWO_PI * SAI_TONE_HZ) /
                     (double)RESOLVED_SAI_TEST_SAMPLE_RATE_HZ;
    g_sai_tone_coef = 2.0 * cos(w);
    g_sai_tone_y1   = SAI_TONE_AMP * sin(-1.0 * w);   /* y[-1] */
    g_sai_tone_y2   = SAI_TONE_AMP * sin(-2.0 * w);   /* y[-2] */
}

static void local_sai_fill_tone_into( int32_t *dst )   /* one block, continuous phase */
{
    for( uint32_t n = 0u; n < (uint32_t)RESOLVED_SAI_TEST_BLOCK_FRAMES; n++ )
    {
        double y0 = (g_sai_tone_coef * g_sai_tone_y1) - g_sai_tone_y2;   /* = amp*sin(w*n) */
        g_sai_tone_y2 = g_sai_tone_y1;
        g_sai_tone_y1 = y0;
        int32_t  s  = (int32_t)y0 & (int32_t)0xFFFFFF00;
        int32_t *fr = &dst[ n * RESOLVED_SAI_TEST_SLOTS_PER_FRAME ];
        for( uint32_t k = 0u; k < (uint32_t)RESOLVED_SAI_TEST_SLOTS_PER_FRAME; k++ )
        {
            fr[k] = (k < 2u) ? s : 0;
        }
    }
}
#endif //TONE || HYBRID_IN_ORIG_OUT_WRAP

#if RESOLVED_SAI_TEST_HYBRID_TX_ENABLED
/* Config 2 (output via wrapper Send) DOUBLE BUFFER: two TX buffers, only ever refill
 * the one that has already completed -- never the in-flight buffer. Stimulus = tone. */
static int32_t g_sai_tx_db[2][SAI_LIVE_BLOCK_SAMPLES];
static volatile uint32_t g_sai_tx_armed = 0u;   /* index currently handed to Send */
#endif // RESOLVED_SAI_TEST_HYBRID_TX_ENABLED

#if RESOLVED_SAI_TEST_LIVE_ENABLED && !RESOLVED_SAI_TEST_TONE_ENABLED && \
    !RESOLVED_SAI_TEST_HYBRID_TX_ENABLED
/* Full loopback TX DOUBLE BUFFER (fix): RECEIVE_COMPLETE writes the received block
 * into the BACK buffer; SEND_COMPLETE arms that prepared buffer and flips. The
 * in-flight Send buffer is never overwritten (removes the single-buffer "ghost"). */
static int32_t g_sai_lb_db[2][SAI_LIVE_BLOCK_SAMPLES];
static volatile uint32_t g_sai_lb_armed = 0u;   /* index currently handed to Send */
#endif //full-loopback double buffer

#if RESOLVED_SAI_TEST_KEEPALIVE_ENABLED && !RESOLVED_SAI_TEST_TONE_ENABLED && \
    !RESOLVED_SAI_TEST_HYBRID_TX_ENABLED
/* ~0.01 full-scale (-40 dBFS), 24-bit aligned, in Q31 int32 (matches flip4's gain). */
#define SAI_LIVE_KA_AMP   ((int32_t)21474836 & (int32_t)0xFFFFFF00)
static int8_t g_sai_ka_sign = 1;

static inline int32_t local_sat_add_i32( int32_t a, int32_t b )
{
    int64_t s = (int64_t)a + (int64_t)b;
    if( s > (int64_t)INT32_MAX ) { s = (int64_t)INT32_MAX; }
    else if( s < (int64_t)INT32_MIN ) { s = (int64_t)INT32_MIN; }
    return (int32_t)s;
}
#endif // RESOLVED_SAI_TEST_KEEPALIVE_ENABLED && !TONE && !HYBRID

static void local_sai_live_event( uint32_t event )
{
#if RESOLVED_SAI_TEST_TONE_ENABLED
    /* TX-only tone: rewrite the (now-free) buffer AFTER SEND_COMPLETE, then re-send. */
    if( event & ARM_SAI_EVENT_RECEIVE_COMPLETE )
    {
        uint32_t pk = local_sai_abspeak( g_sai_live_rx, SAI_LIVE_BLOCK_SAMPLES );
        if( pk > g_sai_live_rx_peak ) { g_sai_live_rx_peak = pk; }
        g_sai_live_rx_blk++;
        (void)Driver_SAI0.Receive( g_sai_live_rx, SAI_LIVE_BLOCK_SAMPLES );
    }
    if( event & ARM_SAI_EVENT_SEND_COMPLETE )
    {
        local_sai_fill_tone_into( g_sai_live_tx );   // regenerate next block (free buffer)
        uint32_t pk = local_sai_abspeak( g_sai_live_tx, SAI_LIVE_BLOCK_SAMPLES );
        if( pk > g_sai_live_tx_peak ) { g_sai_live_tx_peak = pk; }
        g_sai_live_tx_blk++;
        (void)Driver_SAI0.Send( g_sai_live_tx, SAI_LIVE_BLOCK_SAMPLES );
    }

#elif RESOLVED_SAI_TEST_HYBRID_TX_ENABLED
    /* Config 2 (output via wrapper Send): double-buffered streaming tone. Arm the
     * pre-filled buffer, then refill the one that JUST completed -- never the buffer
     * still in flight. Receive is not used in this mode. */
    if( event & ARM_SAI_EVENT_SEND_COMPLETE )
    {
        uint32_t done = g_sai_tx_armed;      /* completed -> free to refill */
        uint32_t next = done ^ 1u;           /* prepared earlier -> arm now */
        g_sai_tx_armed = next;
        uint32_t pk = local_sai_abspeak( g_sai_tx_db[next], SAI_LIVE_BLOCK_SAMPLES );
        if( pk > g_sai_live_tx_peak ) { g_sai_live_tx_peak = pk; }
        g_sai_live_tx_blk++;
        (void)Driver_SAI0.Send( g_sai_tx_db[next], SAI_LIVE_BLOCK_SAMPLES );
        local_sai_fill_tone_into( g_sai_tx_db[done] );   /* refill the free buffer */
    }

#else
    /* Full loopback (input wrapper + output wrapper), DOUBLE-BUFFERED: copy the
     * received block into the BACK buffer on RECEIVE_COMPLETE, arm it on the next
     * SEND_COMPLETE. The in-flight Send buffer is never touched. */
    if( event & ARM_SAI_EVENT_RECEIVE_COMPLETE )
    {
        uint32_t pk = local_sai_abspeak( g_sai_live_rx, SAI_LIVE_BLOCK_SAMPLES );
        if( pk > g_sai_live_rx_peak ) { g_sai_live_rx_peak = pk; }
        g_sai_live_rx_blk++;
        uint32_t back = g_sai_lb_armed ^ 1u;                      /* not the in-flight buffer */
        memcpy( g_sai_lb_db[back], g_sai_live_rx, sizeof(g_sai_lb_db[back]) );  // loopback
#if RESOLVED_SAI_TEST_KEEPALIVE_ENABLED
        {
            int8_t sgn = g_sai_ka_sign;
            for( uint32_t n = 0u; n < (uint32_t)RESOLVED_SAI_TEST_BLOCK_FRAMES; n++ )
            {
                int32_t  ka = (sgn > 0) ? SAI_LIVE_KA_AMP : -SAI_LIVE_KA_AMP;
                int32_t *fr = &g_sai_lb_db[back][ n * RESOLVED_SAI_TEST_SLOTS_PER_FRAME ];
                fr[0] = local_sat_add_i32( fr[0], ka );
                fr[1] = local_sat_add_i32( fr[1], ka );
                sgn = (int8_t)-sgn;
            }
            g_sai_ka_sign = sgn;
        }
#endif // RESOLVED_SAI_TEST_KEEPALIVE_ENABLED
        (void)Driver_SAI0.Receive( g_sai_live_rx, SAI_LIVE_BLOCK_SAMPLES );
    }
    if( event & ARM_SAI_EVENT_SEND_COMPLETE )
    {
        uint32_t next = g_sai_lb_armed ^ 1u;     /* the buffer RECEIVE just filled */
        g_sai_lb_armed = next;
        uint32_t pk = local_sai_abspeak( g_sai_lb_db[next], SAI_LIVE_BLOCK_SAMPLES );
        if( pk > g_sai_live_tx_peak ) { g_sai_live_tx_peak = pk; }
        g_sai_live_tx_blk++;
        (void)Driver_SAI0.Send( g_sai_lb_db[next], SAI_LIVE_BLOCK_SAMPLES );
    }
#endif
}


void audio_transport_sai_live_start( void )
{
    // LIVE wrapper loopback: drive the stream through the CMSIS-SAI wrapper instead
    // of the demo DSP. PowerControl(FULL) registers the wrapper's block callback;
    // CONFIGURE applies the validated format while stopped; CONTROL_TX enable starts
    // the stream. The app arms a Receive+Send pair and keeps them re-armed in
    // local_sai_live_event() for a continuous passthrough.
    int32_t sai_ret;
    sai_ret = Driver_SAI0.Initialize( local_sai_live_event );
    printf(" [SAI-LIVE] Initialize ret=%ld\n", (long)sai_ret );
    sai_ret = Driver_SAI0.PowerControl( ARM_POWER_FULL );
    printf(" [SAI-LIVE] PowerControl(FULL) ret=%ld\n", (long)sai_ret );
  #if RESOLVED_SAI_TEST_SLOTS_PER_FRAME == 2u
    sai_ret = Driver_SAI0.Control( ARM_SAI_CONFIGURE_TX | ARM_SAI_MODE_SLAVE |
                               ARM_SAI_PROTOCOL_I2S | ARM_SAI_DATA_SIZE(32) |
                               ARM_SAI_MCLK_PIN_INPUT, 0u,
                               (uint32_t)RESOLVED_SAI_TEST_SAMPLE_RATE_HZ );
  #else
    sai_ret = Driver_SAI0.Control( ARM_SAI_CONFIGURE_TX | ARM_SAI_MODE_SLAVE |
                               ARM_SAI_PROTOCOL_USER | ARM_SAI_DATA_SIZE(32) |
                               ARM_SAI_MCLK_PIN_INPUT,
                               ARM_SAI_SLOT_COUNT(RESOLVED_SAI_TEST_SLOTS_PER_FRAME),
                               (uint32_t)RESOLVED_SAI_TEST_SAMPLE_RATE_HZ );
  #endif // RESOLVED_SAI_TEST_SLOTS_PER_FRAME == 2u
    printf(" [SAI-LIVE] CONFIGURE_TX ret=%ld\n", (long)sai_ret );

#if RESOLVED_SAI_TEST_TONE_ENABLED
    /* Output-path isolation: TX-only tone (Receive armed for RX instrumentation). */
    printf(" [SAI-LIVE] MODE = TX-only TONE  (output=WRAPPER Send; slots0/1 ~-6dBFS 800Hz)\n" );
    local_sai_tone_init();
    local_sai_fill_tone_into( g_sai_live_tx );
    (void)Driver_SAI0.Receive( g_sai_live_rx, SAI_LIVE_BLOCK_SAMPLES );
    sai_ret = Driver_SAI0.Send( g_sai_live_tx, SAI_LIVE_BLOCK_SAMPLES );
    printf(" [SAI-LIVE] Send(tone) ret=%ld\n", (long)sai_ret );

#elif RESOLVED_SAI_TEST_HYBRID_TX_ENABLED
    /* Config 2: output via wrapper Send, DOUBLE-BUFFERED streaming tone (Receive
     * unused). Pre-fill both buffers; arm Send(buf0). */
    printf(" [SAI-LIVE] MODE = Config2  input=orig(gen) / output=WRAPPER Send (double-buffered)\n" );
    local_sai_tone_init();
    local_sai_fill_tone_into( g_sai_tx_db[0] );
    local_sai_fill_tone_into( g_sai_tx_db[1] );
    g_sai_tx_armed = 0u;
    sai_ret = Driver_SAI0.Send( g_sai_tx_db[0], SAI_LIVE_BLOCK_SAMPLES );
    printf(" [SAI-LIVE] Send(db0) ret=%ld\n", (long)sai_ret );

#else
    /* Full loopback: input wrapper + output wrapper, DOUBLE-BUFFERED (arm Receive +
     * Send db0). block 0 = silence; from block 1 on, output = received input. */
    printf(" [SAI-LIVE] MODE = FULL loopback (input=WRAPPER / output=WRAPPER, double-buffered)\n" );
#if RESOLVED_SAI_TEST_KEEPALIVE_ENABLED
    printf(" [SAI-LIVE]   + inaudible ~24kHz keepalive\n" );
#endif
    memset( g_sai_lb_db[0], 0, sizeof(g_sai_lb_db[0]) );
    g_sai_lb_armed = 0u;
    sai_ret = Driver_SAI0.Receive( g_sai_live_rx, SAI_LIVE_BLOCK_SAMPLES );
    printf(" [SAI-LIVE] Receive ret=%ld\n", (long)sai_ret );
    sai_ret = Driver_SAI0.Send( g_sai_lb_db[0], SAI_LIVE_BLOCK_SAMPLES );
    printf(" [SAI-LIVE] Send ret=%ld\n", (long)sai_ret );
#endif

    sai_ret = Driver_SAI0.Control( ARM_SAI_CONTROL_TX, 1u, 0u );           // enable -> start()
    printf(" [SAI-LIVE] CONTROL_TX(en) ret=%ld block_samples=%lu\n",
           (long)sai_ret, (unsigned long)SAI_LIVE_BLOCK_SAMPLES );
}


bool audio_transport_sai_live_stop( void )
{
    // SINGLE-mode teardown of the wrapper route (counterpart to _start). Disable TX (stops the
    // stream), abort any armed Send/Receive so no transfer is left dangling, then PowerControl(OFF)
    // -- the wrapper's OFF path runs inst_stop(spi1) + close() internally (HAL SINGLE contract).
    // Keep the FIRST non-OK return so the caller can surface a real failure rather than hide it.
    int32_t first_bad = ARM_DRIVER_OK;
    int32_t rc;

    rc = Driver_SAI0.Control( ARM_SAI_CONTROL_TX, 0u, 0u );   // disable TX -> wrapper stops stream
    printf(" [SAI-LIVE] CONTROL_TX(dis) ret=%ld\n", (long)rc );
    if( ( rc != ARM_DRIVER_OK ) && ( first_bad == ARM_DRIVER_OK ) ) { first_bad = rc; }

    (void)Driver_SAI0.Control( ARM_SAI_ABORT_SEND,    0u, 0u );
    (void)Driver_SAI0.Control( ARM_SAI_ABORT_RECEIVE, 0u, 0u );

    rc = Driver_SAI0.PowerControl( ARM_POWER_OFF );          // OFF -> inst_stop(spi1) + close()
    printf(" [SAI-LIVE] PowerControl(OFF) ret=%ld\n", (long)rc );
    if( ( rc != ARM_DRIVER_OK ) && ( first_bad == ARM_DRIVER_OK ) ) { first_bad = rc; }

    return ( first_bad == ARM_DRIVER_OK );
}


void audio_transport_sai_live_dbg_print( void )
{
    // Loopback localiser: rxblk/txblk = copy-layer COMPLETE counts (must climb);
    // rxpeak = |captured input| (input side OK if >0); txpeak = |sent output|.
    // tx_busy/rx_busy from GetStatus show whether a transfer is currently armed.
    ARM_SAI_STATUS ss = Driver_SAI0.GetStatus();
    printf("SAI-LIVE: rxblk=%lu txblk=%lu rxpeak=%lu txpeak=%lu busy(tx,rx)=(%u,%u) uf/of=(%u,%u)\n",
           (unsigned long)g_sai_live_rx_blk, (unsigned long)g_sai_live_tx_blk,
           (unsigned long)g_sai_live_rx_peak, (unsigned long)g_sai_live_tx_peak,
           (unsigned)ss.tx_busy, (unsigned)ss.rx_busy,
           (unsigned)ss.tx_underflow, (unsigned)ss.rx_overflow);
    g_sai_live_rx_peak = 0u;
    g_sai_live_tx_peak = 0u;
}

#endif // RESOLVED_SAI_TEST_LIVE_ENABLED
