/*
 * nora_gpio_event_dspic33ak.c
 * ----------------------
 * Thin dsPIC33AK Change Notification (CN) event dispatcher for GPIO pins.
 *
 * The app/example owns the actual CN interrupt vector and forwards it here.
 * This keeps vector ownership out of the GPIO core while allowing small
 * validation apps to attach callbacks to selected pins.
 */

#include "nora_gpio_event.h"

#include <stddef.h>
#include <xc.h>


//===========================================================
// Definition
//===========================================================

#define NORA_GPIO_EVENT_PORT_COUNT    8u
#define NORA_GPIO_EVENT_PIN_COUNT     16u
#define NORA_GPIO_EVENT_CNCON_CNSTYLE 0x00000800u
#define NORA_GPIO_EVENT_CNCON_ON      0x00008000u

typedef struct
{
    volatile uint32_t *port;
    volatile uint32_t *cncon;
    volatile uint32_t *cnen0;
    volatile uint32_t *cnen1;
    volatile uint32_t *cnf;
} nora_gpio_event_regs_t;

typedef struct
{
    nora_gpio_pin_t            pin;
    nora_gpio_event_edge_t     trigger;
    nora_gpio_event_callback_t callback;
    void                           *user_data;
    bool                            previous_high;
} nora_gpio_event_slot_t;

#define NORA_GPIO_EVENT_PORT_ROW(L) \
    { &PORT##L, &CNCON##L, &CNEN0##L, &CNEN1##L, &CNF##L }
#define NORA_GPIO_EVENT_PORT_NONE \
    { 0, 0, 0, 0, 0 }

/* Availability below is decided by the DFP bit aliases this driver actually
 * writes (_CNxIF / _CNxIE / _CNxIP), not by IFSn/IECn bank numbers. The bank
 * differs per device (CNA..CND sit in IFS3 on AK512, CNE..CNH in IFS9), and
 * encoding that here is exactly the per-device knowledge the alias form removes.
 *
 * The conditions are spelled out rather than generated by a helper macro:
 * producing `defined` through macro expansion is undefined behaviour
 * (-Wexpansion-to-defined).
 *
 * A port whose change-notification registers exist but whose IRQ aliases are
 * missing would silently lose event support, so that combination is a hard
 * error instead of a quiet NORA_GPIO_EVENT_PORT_NONE row. */
#if defined(PORTA) && defined(CNCONA) && defined(CNEN0A) && defined(CNEN1A) && defined(CNFA) \
    && !(defined(_CNAIF) && defined(_CNAIE) && defined(_CNAIP))
#error "PORTA change-notification registers exist but _CNAIF/_CNAIE/_CNAIP are missing from the DFP"
#endif
#if defined(PORTB) && defined(CNCONB) && defined(CNEN0B) && defined(CNEN1B) && defined(CNFB) \
    && !(defined(_CNBIF) && defined(_CNBIE) && defined(_CNBIP))
#error "PORTB change-notification registers exist but _CNBIF/_CNBIE/_CNBIP are missing from the DFP"
#endif
#if defined(PORTC) && defined(CNCONC) && defined(CNEN0C) && defined(CNEN1C) && defined(CNFC) \
    && !(defined(_CNCIF) && defined(_CNCIE) && defined(_CNCIP))
#error "PORTC change-notification registers exist but _CNCIF/_CNCIE/_CNCIP are missing from the DFP"
#endif
#if defined(PORTD) && defined(CNCOND) && defined(CNEN0D) && defined(CNEN1D) && defined(CNFD) \
    && !(defined(_CNDIF) && defined(_CNDIE) && defined(_CNDIP))
#error "PORTD change-notification registers exist but _CNDIF/_CNDIE/_CNDIP are missing from the DFP"
#endif
#if defined(PORTE) && defined(CNCONE) && defined(CNEN0E) && defined(CNEN1E) && defined(CNFE) \
    && !(defined(_CNEIF) && defined(_CNEIE) && defined(_CNEIP))
#error "PORTE change-notification registers exist but _CNEIF/_CNEIE/_CNEIP are missing from the DFP"
#endif
#if defined(PORTF) && defined(CNCONF) && defined(CNEN0F) && defined(CNEN1F) && defined(CNFF) \
    && !(defined(_CNFIF) && defined(_CNFIE) && defined(_CNFIP))
#error "PORTF change-notification registers exist but _CNFIF/_CNFIE/_CNFIP are missing from the DFP"
#endif
#if defined(PORTG) && defined(CNCONG) && defined(CNEN0G) && defined(CNEN1G) && defined(CNFG) \
    && !(defined(_CNGIF) && defined(_CNGIE) && defined(_CNGIP))
#error "PORTG change-notification registers exist but _CNGIF/_CNGIE/_CNGIP are missing from the DFP"
#endif
#if defined(PORTH) && defined(CNCONH) && defined(CNEN0H) && defined(CNEN1H) && defined(CNFH) \
    && !(defined(_CNHIF) && defined(_CNHIE) && defined(_CNHIP))
#error "PORTH change-notification registers exist but _CNHIF/_CNHIE/_CNHIP are missing from the DFP"
#endif


//===========================================================
// Function Prototype
//===========================================================

static const nora_gpio_event_regs_t *nora_gpio_event_regs_for(nora_gpio_pin_t pin);
static unsigned                            nora_gpio_event_port_index(nora_gpio_pin_t pin);
static uint8_t                            nora_gpio_event_bit_index(nora_gpio_pin_t pin);
static uint32_t                           nora_gpio_event_mask(nora_gpio_pin_t pin);
static bool                               nora_gpio_event_trigger_valid(nora_gpio_event_edge_t trigger);
static bool                               nora_gpio_event_trigger_matches(nora_gpio_event_edge_t trigger,
                                                                              nora_gpio_event_edge_t actual_edge);
static bool                               nora_gpio_event_irq_set_priority(unsigned port_index, uint8_t priority);
static bool                               nora_gpio_event_irq_clear_flag(unsigned port_index);
static bool                               nora_gpio_event_irq_flag_is_set(unsigned port_index,
                                                                              bool *flag_set);
static bool                               nora_gpio_event_irq_get_enable(unsigned port_index, bool *enabled);
static bool                               nora_gpio_event_irq_set_enable(unsigned port_index, bool enable);


//===========================================================
// Variables
//===========================================================

static const nora_gpio_event_regs_t s_event_regs[NORA_GPIO_EVENT_PORT_COUNT] =
{
#if defined(PORTA) && defined(CNCONA) && defined(CNEN0A) && defined(CNEN1A) && defined(CNFA) \
    && defined(_CNAIF) && defined(_CNAIE) && defined(_CNAIP)
    NORA_GPIO_EVENT_PORT_ROW(A),                             /* [0] PORTA */
#else
    NORA_GPIO_EVENT_PORT_NONE,
#endif
#if defined(PORTB) && defined(CNCONB) && defined(CNEN0B) && defined(CNEN1B) && defined(CNFB) \
    && defined(_CNBIF) && defined(_CNBIE) && defined(_CNBIP)
    NORA_GPIO_EVENT_PORT_ROW(B),                             /* [1] PORTB */
#else
    NORA_GPIO_EVENT_PORT_NONE,
#endif
#if defined(PORTC) && defined(CNCONC) && defined(CNEN0C) && defined(CNEN1C) && defined(CNFC) \
    && defined(_CNCIF) && defined(_CNCIE) && defined(_CNCIP)
    NORA_GPIO_EVENT_PORT_ROW(C),                             /* [2] PORTC */
#else
    NORA_GPIO_EVENT_PORT_NONE,
#endif
#if defined(PORTD) && defined(CNCOND) && defined(CNEN0D) && defined(CNEN1D) && defined(CNFD) \
    && defined(_CNDIF) && defined(_CNDIE) && defined(_CNDIP)
    NORA_GPIO_EVENT_PORT_ROW(D),                             /* [3] PORTD */
#else
    NORA_GPIO_EVENT_PORT_NONE,
#endif
#if defined(PORTE) && defined(CNCONE) && defined(CNEN0E) && defined(CNEN1E) && defined(CNFE) \
    && defined(_CNEIF) && defined(_CNEIE) && defined(_CNEIP)
    NORA_GPIO_EVENT_PORT_ROW(E),                             /* [4] PORTE */
#else
    NORA_GPIO_EVENT_PORT_NONE,
#endif
#if defined(PORTF) && defined(CNCONF) && defined(CNEN0F) && defined(CNEN1F) && defined(CNFF) \
    && defined(_CNFIF) && defined(_CNFIE) && defined(_CNFIP)
    NORA_GPIO_EVENT_PORT_ROW(F),                             /* [5] PORTF */
#else
    NORA_GPIO_EVENT_PORT_NONE,
#endif
#if defined(PORTG) && defined(CNCONG) && defined(CNEN0G) && defined(CNEN1G) && defined(CNFG) \
    && defined(_CNGIF) && defined(_CNGIE) && defined(_CNGIP)
    NORA_GPIO_EVENT_PORT_ROW(G),                             /* [6] PORTG */
#else
    NORA_GPIO_EVENT_PORT_NONE,
#endif
#if defined(PORTH) && defined(CNCONH) && defined(CNEN0H) && defined(CNEN1H) && defined(CNFH) \
    && defined(_CNHIF) && defined(_CNHIE) && defined(_CNHIP)
    NORA_GPIO_EVENT_PORT_ROW(H),                             /* [7] PORTH */
#else
    NORA_GPIO_EVENT_PORT_NONE,
#endif
};

static nora_gpio_event_slot_t s_event_slots[NORA_GPIO_EVENT_PORT_COUNT][NORA_GPIO_EVENT_PIN_COUNT];
static volatile uint32_t s_event_owned_masks[NORA_GPIO_EVENT_PORT_COUNT];


//===========================================================
// Global Function
//===========================================================

bool nora_gpio_event_attach(nora_gpio_pin_t pin,
                                 nora_gpio_event_edge_t trigger,
                                 nora_gpio_event_callback_t callback,
                                 void *user_data)
{
    const nora_gpio_event_regs_t *regs = nora_gpio_event_regs_for(pin);
    unsigned port_index = nora_gpio_event_port_index(pin);
    uint8_t bit_index = nora_gpio_event_bit_index(pin);
    uint32_t mask = nora_gpio_event_mask(pin);

    if ((regs == 0) || (callback == 0) || !nora_gpio_event_trigger_valid(trigger))
    {
        return false;
    }

    *regs->cnen0 &= ~mask;
    *regs->cnen1 &= ~mask;
    *regs->cnf          &= ~mask;
    (void)nora_gpio_event_irq_clear_flag(port_index);

    s_event_slots[port_index][bit_index].pin       = pin;
    s_event_slots[port_index][bit_index].trigger   = trigger;
    s_event_slots[port_index][bit_index].callback  = callback;
    s_event_slots[port_index][bit_index].user_data = user_data;
    s_event_slots[port_index][bit_index].previous_high = ((*regs->port & mask) != 0u);
    s_event_owned_masks[port_index] |= mask;

    *regs->cncon |= (NORA_GPIO_EVENT_CNCON_CNSTYLE | NORA_GPIO_EVENT_CNCON_ON);

    *regs->cnen0 |= mask;
    *regs->cnen1 |= mask;

    return true;
}

bool nora_gpio_event_detach(nora_gpio_pin_t pin)
{
    const nora_gpio_event_regs_t *regs = nora_gpio_event_regs_for(pin);
    unsigned port_index = nora_gpio_event_port_index(pin);
    uint8_t bit_index = nora_gpio_event_bit_index(pin);
    uint32_t mask = nora_gpio_event_mask(pin);

    if (regs == 0)
    {
        return false;
    }

    *regs->cnen0 &= ~mask;
    *regs->cnen1 &= ~mask;
    *regs->cnf          &= ~mask;
    (void)nora_gpio_event_irq_clear_flag(port_index);

    s_event_slots[port_index][bit_index].pin       = 0u;
    s_event_slots[port_index][bit_index].trigger   = NORA_GPIO_EVENT_EDGE_NONE;
    s_event_slots[port_index][bit_index].callback  = 0;
    s_event_slots[port_index][bit_index].user_data = 0;
    s_event_slots[port_index][bit_index].previous_high = false;
    s_event_owned_masks[port_index] &= ~mask;

    return true;
}

bool nora_gpio_event_irq_enable(nora_gpio_pin_t pin, uint8_t priority)
{
    const nora_gpio_event_regs_t *regs = nora_gpio_event_regs_for(pin);
    unsigned port_index = nora_gpio_event_port_index(pin);

    if ((regs == 0) || (priority > 7u))
    {
        return false;
    }
    if (!nora_gpio_event_irq_set_priority(port_index, priority))
    {
        return false;
    }
    if (!nora_gpio_event_irq_clear_flag(port_index))
    {
        return false;
    }
    return nora_gpio_event_irq_set_enable(port_index, true);
}

bool nora_gpio_event_irq_disable(nora_gpio_pin_t pin)
{
    const nora_gpio_event_regs_t *regs = nora_gpio_event_regs_for(pin);
    unsigned port_index = nora_gpio_event_port_index(pin);

    if (regs == 0)
    {
        return false;
    }
    if (!nora_gpio_event_irq_set_enable(port_index, false))
    {
        return false;
    }
    return nora_gpio_event_irq_clear_flag(port_index);
}

bool nora_gpio_event_irq_is_enabled(nora_gpio_pin_t pin, bool *enabled)
{
    const nora_gpio_event_regs_t *regs = nora_gpio_event_regs_for(pin);
    unsigned port_index = nora_gpio_event_port_index(pin);

    if ((regs == 0) || (enabled == 0))
    {
        return false;
    }
    return nora_gpio_event_irq_get_enable(port_index, enabled);
}

bool nora_gpio_event_irq_set_enabled(nora_gpio_pin_t pin, bool enable)
{
    const nora_gpio_event_regs_t *regs = nora_gpio_event_regs_for(pin);
    unsigned port_index = nora_gpio_event_port_index(pin);

    if (regs == 0)
    {
        return false;
    }
    return nora_gpio_event_irq_set_enable(port_index, enable);
}

bool nora_gpio_event_rp_attach(nora_gpio_rp_t rp,
                                    nora_gpio_event_edge_t trigger,
                                    nora_gpio_event_callback_t callback,
                                    void *user_data)
{
    nora_gpio_pin_t pin;

    if (!nora_gpio_pin_from_rp(rp, &pin))
    {
        return false;
    }
    return nora_gpio_event_attach(pin, trigger, callback, user_data);
}

bool nora_gpio_event_rp_detach(nora_gpio_rp_t rp)
{
    nora_gpio_pin_t pin;

    if (!nora_gpio_pin_from_rp(rp, &pin))
    {
        return false;
    }
    return nora_gpio_event_detach(pin);
}

bool nora_gpio_event_rp_irq_enable(nora_gpio_rp_t rp, uint8_t priority)
{
    nora_gpio_pin_t pin;

    if (!nora_gpio_pin_from_rp(rp, &pin))
    {
        return false;
    }
    return nora_gpio_event_irq_enable(pin, priority);
}

bool nora_gpio_event_rp_irq_disable(nora_gpio_rp_t rp)
{
    nora_gpio_pin_t pin;

    if (!nora_gpio_pin_from_rp(rp, &pin))
    {
        return false;
    }
    return nora_gpio_event_irq_disable(pin);
}

bool nora_gpio_event_rp_irq_is_enabled(nora_gpio_rp_t rp, bool *enabled)
{
    nora_gpio_pin_t pin;

    if (!nora_gpio_pin_from_rp(rp, &pin))
    {
        return false;
    }
    return nora_gpio_event_irq_is_enabled(pin, enabled);
}

bool nora_gpio_event_rp_irq_set_enabled(nora_gpio_rp_t rp, bool enable)
{
    nora_gpio_pin_t pin;

    if (!nora_gpio_pin_from_rp(rp, &pin))
    {
        return false;
    }
    return nora_gpio_event_irq_set_enabled(pin, enable);
}

void nora_gpio_event_process_isr(void)
{
    uint8_t port_index;

    for (port_index = 0u; port_index < NORA_GPIO_EVENT_PORT_COUNT; port_index++)
    {
        const nora_gpio_event_regs_t *regs = &s_event_regs[port_index];
        uint32_t pending_mask;
        uint32_t port_level;
        uint8_t bit_index;

        if (regs->port == 0)
        {
            continue;
        }

        pending_mask = *regs->cnf & s_event_owned_masks[port_index];
        if (pending_mask == 0u)
        {
            bool flag_set = false;

            if ((s_event_owned_masks[port_index] != 0u) &&
                nora_gpio_event_irq_flag_is_set(port_index, &flag_set) &&
                flag_set)
            {
                (void)nora_gpio_event_irq_clear_flag(port_index);
            }
            continue;
        }

        port_level = *regs->port;

        for (bit_index = 0u; bit_index < NORA_GPIO_EVENT_PIN_COUNT; bit_index++)
        {
            uint32_t bit_mask = (uint32_t)1u << bit_index;
            nora_gpio_event_slot_t *slot;
            nora_gpio_event_edge_t actual_edge;
            bool current_high;

            if ((pending_mask & bit_mask) == 0u)
            {
                continue;
            }

            slot = &s_event_slots[port_index][bit_index];
            current_high = ((port_level & bit_mask) != 0u);
            if (current_high == slot->previous_high)
            {
                continue;
            }

            actual_edge = current_high ?
                          NORA_GPIO_EVENT_EDGE_RISING :
                          NORA_GPIO_EVENT_EDGE_FALLING;
            slot->previous_high = current_high;

            if ((slot->callback != 0) &&
                nora_gpio_event_trigger_matches(slot->trigger, actual_edge))
            {
                slot->callback(slot->pin, actual_edge, slot->user_data);
            }
        }

        *regs->cnf &= ~pending_mask;
        (void)nora_gpio_event_irq_clear_flag(port_index);
    }
}


//===========================================================
// Local Function
//===========================================================

static const nora_gpio_event_regs_t *nora_gpio_event_regs_for(nora_gpio_pin_t pin)
{
    unsigned port_index = nora_gpio_event_port_index(pin);

    if (port_index >= NORA_GPIO_EVENT_PORT_COUNT)
    {
        return 0;
    }
    if (s_event_regs[port_index].port == 0)
    {
        return 0;
    }
    return &s_event_regs[port_index];
}

static unsigned nora_gpio_event_port_index(nora_gpio_pin_t pin)
{
    return (unsigned)(pin >> 4);
}

static uint8_t nora_gpio_event_bit_index(nora_gpio_pin_t pin)
{
    return (uint8_t)(pin & 0x0Fu);
}

static uint32_t nora_gpio_event_mask(nora_gpio_pin_t pin)
{
    return (uint32_t)1u << nora_gpio_event_bit_index(pin);
}

static bool nora_gpio_event_trigger_valid(nora_gpio_event_edge_t trigger)
{
    return (trigger == NORA_GPIO_EVENT_EDGE_EITHER);
}

static bool nora_gpio_event_trigger_matches(nora_gpio_event_edge_t trigger,
                                                 nora_gpio_event_edge_t actual_edge)
{
    return ((trigger == NORA_GPIO_EVENT_EDGE_EITHER) ||
            (trigger == actual_edge));
}

static bool nora_gpio_event_irq_set_priority(unsigned port_index, uint8_t priority)
{
    switch (port_index)
    {
#if defined(_CNAIP)
    case NORA_GPIO_PORT_A: _CNAIP = priority; return true;
#endif
#if defined(_CNBIP)
    case NORA_GPIO_PORT_B: _CNBIP = priority; return true;
#endif
#if defined(_CNCIP)
    case NORA_GPIO_PORT_C: _CNCIP = priority; return true;
#endif
#if defined(_CNDIP)
    case NORA_GPIO_PORT_D: _CNDIP = priority; return true;
#endif
#if defined(_CNEIP)
    case NORA_GPIO_PORT_E: _CNEIP = priority; return true;
#endif
#if defined(_CNFIP)
    case NORA_GPIO_PORT_F: _CNFIP = priority; return true;
#endif
#if defined(_CNGIP)
    case NORA_GPIO_PORT_G: _CNGIP = priority; return true;
#endif
#if defined(_CNHIP)
    case NORA_GPIO_PORT_H: _CNHIP = priority; return true;
#endif
    default: return false;
    }
}

static bool nora_gpio_event_irq_clear_flag(unsigned port_index)
{
    switch (port_index)
    {
#if defined(_CNAIF)
    case NORA_GPIO_PORT_A: _CNAIF = 0u; return true;
#endif
#if defined(_CNBIF)
    case NORA_GPIO_PORT_B: _CNBIF = 0u; return true;
#endif
#if defined(_CNCIF)
    case NORA_GPIO_PORT_C: _CNCIF = 0u; return true;
#endif
#if defined(_CNDIF)
    case NORA_GPIO_PORT_D: _CNDIF = 0u; return true;
#endif
#if defined(_CNEIF)
    case NORA_GPIO_PORT_E: _CNEIF = 0u; return true;
#endif
#if defined(_CNFIF)
    case NORA_GPIO_PORT_F: _CNFIF = 0u; return true;
#endif
#if defined(_CNGIF)
    case NORA_GPIO_PORT_G: _CNGIF = 0u; return true;
#endif
#if defined(_CNHIF)
    case NORA_GPIO_PORT_H: _CNHIF = 0u; return true;
#endif
    default: return false;
    }
}

/* Read-only twin of the clear above, used by the dispatcher to decide whether a
 * flag is left asserted with no owned CNF bit behind it (spurious / already
 * handled).  Reading a bit alias is a plain byte read, no hazard. */
static bool nora_gpio_event_irq_flag_is_set(unsigned port_index, bool *flag_set)
{
    if (flag_set == 0)
    {
        return false;
    }

    switch (port_index)
    {
#if defined(_CNAIF)
    case NORA_GPIO_PORT_A: *flag_set = (_CNAIF != 0u); return true;
#endif
#if defined(_CNBIF)
    case NORA_GPIO_PORT_B: *flag_set = (_CNBIF != 0u); return true;
#endif
#if defined(_CNCIF)
    case NORA_GPIO_PORT_C: *flag_set = (_CNCIF != 0u); return true;
#endif
#if defined(_CNDIF)
    case NORA_GPIO_PORT_D: *flag_set = (_CNDIF != 0u); return true;
#endif
#if defined(_CNEIF)
    case NORA_GPIO_PORT_E: *flag_set = (_CNEIF != 0u); return true;
#endif
#if defined(_CNFIF)
    case NORA_GPIO_PORT_F: *flag_set = (_CNFIF != 0u); return true;
#endif
#if defined(_CNGIF)
    case NORA_GPIO_PORT_G: *flag_set = (_CNGIF != 0u); return true;
#endif
#if defined(_CNHIF)
    case NORA_GPIO_PORT_H: *flag_set = (_CNHIF != 0u); return true;
#endif
    default: return false;
    }
}

static bool nora_gpio_event_irq_get_enable(unsigned port_index, bool *enabled)
{
    switch (port_index)
    {
#if defined(_CNAIE)
    case NORA_GPIO_PORT_A: *enabled = (_CNAIE != 0u); return true;
#endif
#if defined(_CNBIE)
    case NORA_GPIO_PORT_B: *enabled = (_CNBIE != 0u); return true;
#endif
#if defined(_CNCIE)
    case NORA_GPIO_PORT_C: *enabled = (_CNCIE != 0u); return true;
#endif
#if defined(_CNDIE)
    case NORA_GPIO_PORT_D: *enabled = (_CNDIE != 0u); return true;
#endif
#if defined(_CNEIE)
    case NORA_GPIO_PORT_E: *enabled = (_CNEIE != 0u); return true;
#endif
#if defined(_CNFIE)
    case NORA_GPIO_PORT_F: *enabled = (_CNFIE != 0u); return true;
#endif
#if defined(_CNGIE)
    case NORA_GPIO_PORT_G: *enabled = (_CNGIE != 0u); return true;
#endif
#if defined(_CNHIE)
    case NORA_GPIO_PORT_H: *enabled = (_CNHIE != 0u); return true;
#endif
    default: return false;
    }
}

/*
 * Each arm writes a literal 1 or 0 rather than a computed value.  `_CNxIE = v`
 * with a runtime v compiles to a read-modify-write of the whole IECx byte, and
 * that byte is shared: CNA..CND sit in IEC3<24:31> next to DMA6/7IE and CCP5IE
 * on AK512.  Rewriting it would clobber whichever of those a higher-priority
 * interrupt changed in between.  Branch first, then store a constant, and
 * XC-DSC emits one `bset.b`/`bclr.b`.
 */
static bool nora_gpio_event_irq_set_enable(unsigned port_index, bool enable)
{
    switch (port_index)
    {
#if defined(_CNAIE)
    case NORA_GPIO_PORT_A:
        if (enable) { _CNAIE = 1; } else { _CNAIE = 0; }
        return true;
#endif
#if defined(_CNBIE)
    case NORA_GPIO_PORT_B:
        if (enable) { _CNBIE = 1; } else { _CNBIE = 0; }
        return true;
#endif
#if defined(_CNCIE)
    case NORA_GPIO_PORT_C:
        if (enable) { _CNCIE = 1; } else { _CNCIE = 0; }
        return true;
#endif
#if defined(_CNDIE)
    case NORA_GPIO_PORT_D:
        if (enable) { _CNDIE = 1; } else { _CNDIE = 0; }
        return true;
#endif
#if defined(_CNEIE)
    case NORA_GPIO_PORT_E:
        if (enable) { _CNEIE = 1; } else { _CNEIE = 0; }
        return true;
#endif
#if defined(_CNFIE)
    case NORA_GPIO_PORT_F:
        if (enable) { _CNFIE = 1; } else { _CNFIE = 0; }
        return true;
#endif
#if defined(_CNGIE)
    case NORA_GPIO_PORT_G:
        if (enable) { _CNGIE = 1; } else { _CNGIE = 0; }
        return true;
#endif
#if defined(_CNHIE)
    case NORA_GPIO_PORT_H:
        if (enable) { _CNHIE = 1; } else { _CNHIE = 0; }
        return true;
#endif
    default: return false;
    }
}
